all:
	make -C ./question1
	make -C ./question2
	make -C ./question3
	make -C ./question4


clean:
	make clean -C ./question1
	make clean -C ./question2
	make clean -C ./question3
	make clean -C ./question4
